#!/bin/bash
if [ $# -ne 1 ]; then
    echo "Usage: $0 <source>"
    exit 1
fi

source="$1"
filename=$(basename "$source")
output="/tmp/${filename%.rs}"

rustc "$source" -o "$output"
if [ $? -ne 0 ]; then
    exit 1
fi

"$output"
rm "$output"
