#!/bin/bash
if [ $# -lt 1 ]; then
	echo "Usage: $0 <source> [args...]"
	exit 1
fi

source="$1"
filename=$(basename "$source")
output="/tmp/${filename%.rs}"

rustc "$source" -o "$output"
if [ $? -ne 0 ]; then
	exit 1
fi

shift # remove program name argument
"$output" $@
rm "$output"
